const fs = require('fs');
const path = require('path');

const routesDir = path.join(__dirname, 'route');

const postmanCollection = {
    info: {
        name: "Dharma-cab APIs",
        description: "Autogenerated Postman Collection matching folder structure",
        schema: "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
    },
    item: []
};

function getFolderNode(baseItem, folderName) {
    let folder = baseItem.find(i => i.name === folderName);
    if (!folder) {
        folder = { name: folderName, item: [] };
        baseItem.push(folder);
    }
    return folder;
}

function processFile(filePath, relativePath) {
    const content = fs.readFileSync(filePath, 'utf8');
    const regex = /(?:router|app)\.(get|post|put|delete|patch)\s*\(\s*['"]([^'"]+)['"]/g;

    let match;
    const endpoints = [];
    while ((match = regex.exec(content)) !== null) {
        endpoints.push({ method: match[1].toUpperCase(), routePath: match[2] });
    }

    if (endpoints.length === 0) return;

    // build folder structure
    const folders = path.dirname(relativePath).split(path.sep);
    let currentItem = postmanCollection.item;

    // Create nested Postman folders based on directory
    if (folders[0] !== '.') {
        for (const folder of folders) {
            const folderNode = getFolderNode(currentItem, folder);
            currentItem = folderNode.item;
        }
    }

    // Group inside file name
    const fileName = path.basename(relativePath, '.js');
    const fileFolderNode = getFolderNode(currentItem, fileName);

    const fullPathMatchesAppJs = (p) => {
        if (p.startsWith('/api/') || p.startsWith('/admin/') || p.startsWith('/support/')) {
            return p;
        }
        return p.startsWith('/') ? `/api${p}` : `/api/${p}`;
    }

    endpoints.forEach(ep => {
        let finalPath = ep.routePath;
        // Basic heuristic to guess full path if it's missing /api etc
        // Since we don't have express router stack, we make best effort
        if (!finalPath.startsWith('/admin') && !finalPath.startsWith('/api') && !finalPath.startsWith('/support')) {
            if (relativePath.includes('admin')) {
                if (!finalPath.startsWith('/admin')) {
                    finalPath = `/admin${finalPath.startsWith('/') ? '' : '/'}${finalPath}`;
                }
            } else {
                if (!finalPath.startsWith('/api')) {
                    finalPath = `/api${finalPath.startsWith('/') ? '' : '/'}${finalPath}`;
                }
            }
        }

        // Some routes might already have /admin/cars vs /cars
        // For simplicity, we just use whatever the matched route string was 
        // and let the user adjust base url if needed, but we'll try to prepend properly
        finalPath = ep.routePath.startsWith('/') ? ep.routePath : `/${ep.routePath}`;

        // Many route paths are already full paths like /admin/cars in the files
        // E.g. router.get("/admin/cars")
        // E.g. router.get("/profile") -> mounted on /api -> /api/profile
        if (!finalPath.startsWith('/admin') && !finalPath.startsWith('/api') && !finalPath.startsWith('/support')) {
            if (relativePath.includes('admin')) {
                // some might just be /something under admin 
            } else if (relativePath.includes('customer') || relativePath.includes('rider')) {
                finalPath = `/api${finalPath}`;
            }
        }

        const pathArray = finalPath.replace(/^\//, '').split('/');

        fileFolderNode.item.push({
            name: `${ep.method} ${finalPath}`,
            request: {
                method: ep.method,
                header: [
                    {
                        key: "Authorization",
                        value: "{{Dharma-AdminToken}}",
                        type: "text"
                    }
                ],
                url: {
                    raw: `{{Dharma-baseUrl}}${finalPath}`,
                    host: ["{{Dharma-baseUrl}}"],
                    path: pathArray
                }
            },
            response: []
        });
    });
}

function walkDir(dir, baseDir) {
    const files = fs.readdirSync(dir);
    for (const file of files) {
        const fullPath = path.join(dir, file);
        if (fs.statSync(fullPath).isDirectory()) {
            walkDir(fullPath, baseDir);
        } else if (file.endsWith('.js')) {
            processFile(fullPath, path.relative(baseDir, fullPath));
        }
    }
}

// Ensure postman folder exists
const outputDir = path.join(__dirname, '..', 'postman');
if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
}

walkDir(routesDir, routesDir);

const outputPath = path.join(outputDir, 'Dharma-cab.postman_collection.json');
fs.writeFileSync(outputPath, JSON.stringify(postmanCollection, null, 2));
console.log(`Successfully generated collection at ${outputPath}`);
